name: "CNN_LSTM"

task: "segmentation"

model:
  vocab_size: 95
  emb_dim: 32
  labels_number: 3
  hidden_dim: 256
  n_layers: 3
  dropout: 0.4
  window: [3, 5]
  use_batch_norm: true
  use_attention: false
  use_lstm: true

training:
  batch_size: 16
  num_epochs: 150
  patience: 20
  learning_rate: 1e-3
  device: "cuda"
  random_seed: 42
  optimizer: "AdamW"

device: 'cpu'
