name: "BiLSTM_affix"

task: "lemma_tagger"

model:
  vocab_size: 95
  emb_dim: 32
  hidden_dim: 64
  labels_number: 3
  dropout: 0.2

training:
  random_seed: 42
  batch_size: 32
  device: 'cuda'
  learning_rate: 1e-3
  patience: 20
  num_epochs: 100
  optimizer: "AdamW"

device: 'cpu'